### ISSUE TITLE
Breakpoint for report page is one larger than for grid columns

### ISSUE THREAD

**Issue by akleinsteiber** [eBay/Design-Grid-Overlay#29]
For example, with "Large to Small Breakpoint" set to 600, it will show Large columns at window width 600, but will continue to calculate Small number of columns in the report. The report will be correct at window width 601.

**Comment by tonytopper** [comment]
The actual layout is changing to small at 598 now.   Exactly 600 should be small.   So the point you select should begin the size down.

**Comment by normtronics** [comment]
This is fixed in commit 47f78e89a903a5e398b981eb973454dccd727846
