### ISSUE TITLE
Horizontal grid lines with config options

### ISSUE THREAD

**Issue by jskorupski** [eBay/Design-Grid-Overlay#46]

**Comment by denisinvader** [comment]
would be great. Now i have to use this extension with another one for horizontal grids

**Comment by denisinvader** [comment]
I've made a [prototype](https://github.com/eBay/Design-Grid-Overlay/pull/53) for this issue

**Comment by tonytopper** [comment]
Cleaning spree today.  Closing lots of issues that have been finished.
