### ISSUE TITLE
Create keyboard shortcut to toggle grid overlay on and off

### ISSUE THREAD

**Issue by tonytopper** [eBay/Design-Grid-Overlay#54]
I am not sure if this is even possible.  I imagine it is though.

**Comment by jskorupski** [comment]
This API looks like the way to do it: https://developer.chrome.com/extensions/commands

**Comment by denisinvader** [comment]
I'm almost finished with it

**Comment by tonytopper** [comment]
@happytogether processed the pull requests for this.  Check out what we ended up with.    Thanks @denisinvader
