### ISSUE TITLE
When i refresh the grid reset.

### ISSUE THREAD

**Issue by manuhazen** [eBay/Design-Grid-Overlay#62]
Hi, i'm a frequent and current user of your extension, but, after of your last update when i refresh the grid, the grid's reset at the default settings. I don't know if exists a setting for that but i cannot find it. 

If they you can bring back that option me and my team will be very grateful. 

Thank you in advance.

**Comment by tonytopper** [comment]
We'll look into this.  Thanks.

**Comment by tonytopper** [comment]
Just published 1.0.1.  Let me know if everything is good and I'll close this issue.

**Comment by manuhazen** [comment]
Hey Tony, i tested with few team mates and everything's working like a charm. Thank you, you can close this issue.
