### ISSUE TITLE
Request for an additional feature

### ISSUE THREAD

**Issue by kylejcassaday** [eBay/Design-Grid-Overlay#64]
Hi, I'm a web developer, and I use Design Grid Overlay for almost every project. I have an issue though. Everytime I make a change to a webpage I am designing, I need to refresh the browser with the Grid Overlay showing. The Grid disappears when you refresh the page. Is there anyway you can add a setting that would allow the extension to stay visible after a page reload? It would be extremely useful. 

Thanks for your time.

Kyle Cassaday

**Comment by tonytopper** [comment]
Well you're in luck.  This issue already exists in our queue as issue  #61.   And one of our contributor, @denisinvader, just recently volunteered to help take a look at.   I am going to close this issue.  But do go over and subscribe to #61 so you can stay up to date on that feature's progress.

**Comment by kylejcassaday** [comment]
Ok will do. Thank you.
