### ISSUE TITLE
Shortchut not working in first time

### ISSUE THREAD

**Issue by notrealdev** [eBay/Design-Grid-Overlay#67]
Hi, in first time shortcut not working for me
When page load complete i press `Ctrl+Shift+K`, extension not working.
Then i press button to turn on Design-Grid-Overlay, it's working, then i press `Ctrl+Shift+K`, it's worked
I tried many time but the result is the same
// Chrome windows 10: Version 61.0.3163.79 (Official Build) (64-bit)

**Comment by denisinvader** [comment]
It's okay for now. Shortcut doesn't working because there is no scripts and styles for grid rendering on the page and extension isn't active , they are inserted when grid is rendering by popup.
But it could be fixed, we can insert required code on every page load
