### ISSUE TITLE
Allow to save and share layouts

### ISSUE THREAD

**Issue by santiDotIO** [eBay/Design-Grid-Overlay#69]
Would be great to be able to share grid configurations with the team. Also pretty common for devs to have different grids when working on multiple projects. I'm more interested in the sharing functionality than anything else.

**Comment by HagenMorano** [comment]
Seems this project is not maintained anymore.

@santi6291 Did you end up using another solution that implements this feature?

**Comment by santiDotIO** [comment]
Sadly no
